bro:
  c: "Dude"
  g: "Bro"
  t: "What"
  a: "Like"
awesome:
  a: "Bitching"
  c: "Sweet"
  t: "Tight"
  g: "Feelings"
bandura:
  a: "Learn"
  c: "Share"
  t: "Discover"
  g: "Jetpack"
template:
  a: 
  c: 
  t: 
  g: 